<?
/*------------------------------------------------------
 Test Run Script for GrabYahoo - Yahoo Service Grabber class

 Version 1.5, Created 05/22/2006, Updated 11/03/2010

 Credit for latest fix: Ovidiu

 This class is used to grab Yahoo services like
 Address Book, Messenger List, Number of New Mails

 Copyright (C) 2006 Ehsan Haque

 License: GPL

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
------------------------------------------------------*/

require_once('class.GrabYahoo.php');

// Yahoo! Account Username
$login    = "username";

// Yahoo! Account Password
$password = "password";

// Initializing Class
$yahoo  = new GrabYahoo;

/*
Setting the desired Service
  1. addressbook => Used to grab Yahoo! Address Book
  2. messenger => Used to grab Yahoo! Messenger List
  3. newmail => Used to grab number of new Yahoo! mails
  4. calendar => Used to grab Yahoo! Calendar entries
*/
$yahoo->service = "addressbook";

/*
Set to true if HTTP proxy is required to browse net
  - Setting it to true will require to provide Proxy Host Name and Port number
*/
$yahoo->isUsingProxy = false;

// Set the Proxy Host Name, isUsingProxy is set to true
$yahoo->proxyHost = "";

// Set the Proxy Port Number
$yahoo->proxyPort = "";

// Set the location to save the Cookie Jar File
$yahoo->cookieJarPath = $_SERVER['DOCUMENT_ROOT'] . "/GrabYahoo1.3";

/*
Execute the Service
  - Require to pass Yahoo! Account Username and Password
*/
$yahooList = $yahoo->execService($login, $password);

// Printing the array generated by the Class
dump($yahooList);

/*
Printing new mail status
  - True (1) if there is new mail(s)
  - False (0) if there is no new mail
*/
//$newMailStatus  = $yahoo->getNewMailStatus();
//echo $newMailStatus;

// Use this line to figure out any error generated during the process
echo $yahoo->errorInfo;

function dump($var)
{
  echo "<pre>";
    print_r($var);
  echo "</pre>";
}

?>
